### ISSUE TITLE
how to handle tautomers?

### ISSUE THREAD

**Issue by likun1212** [coleygroup/molpal#32]
Hi

Multiple tautomers could be generted after ligand prepartion, how should I deal with these tautomers, should I add these into pool library?

tautomers  normally have differernt fingerprint.

**Comment by connorcoley** [comment]
Rather than having multiple tautomers as distinct library members, I imagine the best solution would be to have a canonicalization pipeline that tries to standardize representations so this isn't an issue, e.g., using RDKit's standardization with MolVS or roundtripping to/from InChI (if appropriate)

**Comment by likun1212** [comment]
thanks for your reply, this is really helpful.

I am not an expert on machine learning, naively I  thought it is a good thing that providing more information(tautomers) for training the surrogate model.   

so this is just not the case, I think. Thank you!
